### PR TITLE
Sync upstream

### LINKED ISSUE #5: New upstream commit(s)
Upstream changed to e9a73410630fbc46f547ab5c5d24efb2c569bb69

### PR DESCRIPTION
**Pull request by Earlopain**
Closes #5

### CODE REVIEW

**Comment by Earlopain** [comment]
I can't get the newly ported test from https://github.com/unicorn-ruby/unicorn/pull/6/commits/a6000936d9004c31955a3412d9457f5967e23d73 to pass locally, or here in GitHub actions. I'll try to figure out whats wrong with it...

**Comment by Earlopain** [comment]
Something to do with them now running through bundler. In my eyes skipping seems like a fine thing to do.

**Comment by Earlopain** [comment]
@ioquatix should I go ahead an merge? I can do so myself but I don't want to step on your toes or something.

**Comment by ioquatix** [comment]
You are welcome to merge!

**Pull request merged**
